function [fitresult, gof] = createFit(measuredFiltered, actualFiltered)
%CREATEFIT(MEASUREDFILTERED,ACTUALFILTERED)
%  Create a fit.
%
%  Data for 'fit2' fit:
%      X Input : measuredFiltered
%      Y Output: actualFiltered
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Sep-2021 11:06:43


%% Fit: 'fit2'.
[xData, yData] = prepareCurveData( measuredFiltered, actualFiltered );

% Set up fittype and options.
ft = fittype( 'power2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1339.75838411513 -0.619661538444521 1.64892681750268];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fit2' );
h = plot( fitresult, xData, yData );
legend( h, 'actualFiltered vs. measuredFiltered', 'fit2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'measuredFiltered', 'Interpreter', 'none' );
ylabel( 'actualFiltered', 'Interpreter', 'none' );
grid on


