function [fitresult, gof] = createFit(readingsFiltered, distancesFiltered)
%CREATEFIT(READINGSFILTERED,DISTANCESFILTERED)
%  Create a fit.
%
%  Data for 'fit3' fit:
%      X Input : readingsFiltered
%      Y Output: distancesFiltered
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Sep-2021 11:10:04


%% Fit: 'fit3'.
[xData, yData] = prepareCurveData( readingsFiltered, distancesFiltered );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [4632.80597396124 -0.96735758332615];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fit3' );
h = plot( fitresult, xData, yData );
legend( h, 'distancesFiltered vs. readingsFiltered', 'fit3', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'readingsFiltered', 'Interpreter', 'none' );
ylabel( 'distancesFiltered', 'Interpreter', 'none' );
grid on


