function [fitresult, gof] = createFit(distancesFiltered, readingsFiltered)
%CREATEFIT(DISTANCESFILTERED,READINGSFILTERED)
%  Create a fit.
%
%  Data for 'fit4' fit:
%      X Input : distancesFiltered
%      Y Output: readingsFiltered
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Sep-2021 14:11:26


%% Fit: 'fit4'.
[xData, yData] = prepareCurveData( distancesFiltered, readingsFiltered );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [8224.773209451 -1.11297155414937];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fit4' );
h = plot( fitresult, xData, yData );
legend( h, 'readingsFiltered vs. distancesFiltered', 'fit4', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'distancesFiltered', 'Interpreter', 'none' );
ylabel( 'readingsFiltered', 'Interpreter', 'none' );
grid on


