function createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 29-Sep-2021 21:56:01

% Create figure
figure1 = figure('Name','distance_from_data');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','experimental data point','Marker','.',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot1 = plot(X2,Y2,'DisplayName','fitted curve','Color',[1 0 0]);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,118.795,75.6577581638005);
% Create datatip
datatip(plot1,'DataIndex',57);

% Create ylabel
ylabel({'actual distance (in)'},'Interpreter','none');

% Create xlabel
xlabel({'sensor output ('},'Interpreter','none');

% Create title
title({'Calibration Curve of Distances vs. Sensor Outputs'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-3.68663594470047 596.3133640553]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[10.1556420233463 90.1556420233463]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');

